---
title: "VectorByte Training Materials 2023"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

# Overview

## Pre-work and set-up

### Hardware and Software

We will be using [`R`](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have `R` (version 3.6 or higher) installed.

You may use any IDE/ GUI for `R` (VScode, RStudio, Emacs, etc). For most people, [`RStudio`](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and test it before the workshop. We will have a channel on Slack dedicated to software/hardware issues and troubleshooting.

We will also be using Slack for additional support during the training. Please have these installed in advance.

### Pre-requisites

We are assuming familiarity with R basics. In addition, we recommend that you do the following:

1.  Go to [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html), and read+work through the [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html) up to the section on Writing R code. Of course, keep going if you want (although we will cover some similar materials here).

2.  In addition / alternatively to pre-work element (1), here are some resources for brushing up on R [at the end of the Intro R Chapter you can try](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html#readings-and-resources). But there are many more resources online (e.g., [this](https://www.codecademy.com/learn/learn-r) and [this](https://www.dataquest.io/blog/learn-r-for-data-science/) ) -- pick something that suits your learning style.

3.  Review background on [introductory probability and statistics](Stats_review.qmd) ([solutions to exercises](Stats_review_soln.qmd))

4.  Inculcate the coding Jedi inside of you - or the Sith - whatever works.

<br> <br>

## Introduction to the VecTraits database[^1]

[^1]: What is the difference between VectorBiTE and VectorByte? We are glad you asked! [VectorBiTE](http://vectorbite.org/) was an RCN or a research coordination network funded by a 5 year grant from the BBSRC. [VectorByte](https://www.vectorbyte.org/) is hosting this training which is a newly funded NSF grant to establish a global open access data platform to study disease vectors. All the databases have transitioned to VectorByte but the legacy options will still be available on the VectorBiTE website.

-   This component will be delivered live & synchronously. The VecTraits website can be found [here](https://vectorbyte.crc.nd.edu/vectraits-explorer). It might be an idea to explore this prior to the workshop.

[Intro to the VecTraits API](Intro_to_API.qmd)

<br> <br>

## Introduction to traits

-   [Lecture slides](intro_to_traits.pdf)

-   [Cator *et al*. 2020. The Role of Vector Trait Variation in Vector-Borne Disease Dynamics](Cator%20et%20al.%202020.%20The%20Role%20of%20Vector%20Trait%20Variation%20in%20Vector-Borne%20Disease%20Dynamics.pdf)

<br> <br>

## Data Wrangling in R

-   [Practical](data_wrangling.qmd)
-   Datasets:
    -   [Poundhill Data](activities/data/PoundHillData.csv)
    -   [Poundhill Meta Data](activities/data/PoundHillMetaData.csv)
    -   [Huxley et al Trait Data](activities/data/traitdata_Huxleyetal_2021.csv)
    -   [Genome Size](activities/data/GenomeSize.csv)
    -   [Wrangling Practical Data](activities/data/wranglingdataset.csv)

<br> <br>

## Introduction to Linear Models

-   [Lecture Slides](lectures/VB_LinMods.pdf), [Lecture Video 1](https://www.youtube.com/watch?v=oqjzfXDgZY0&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=2), [Lecture Video 2](https://www.youtube.com/watch?v=-VelMqc9z6M&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=1), [Practical](linear_mod_activity.qmd)
-   Datasets:
    -   [Genome Size](activities/data/GenomeSize.csv)
    -   [Huxley *et al.* Trait Data](activities/data/traitdata_Huxleyetal_2021.csv)
    -   [Linear Models Practical Data](activities/data/lmdataset.csv)

<br> <br>

## Nonlinear Modeling (including Thermal Performance Curves -- TPCs)

-   [Lecture Slides](lectures/VB_NLLS.pdf), [Lecture Video](https://www.youtube.com/watch?v=dnZlU2_iQ1k&list=PLrMhLVyZEsORr81gXrfgiq2vX30_brtpF&index=3), [Practical](VB_NLLS_activity.qmd)
-   Datasets:
    -   [csm7I Data](activities/data/csm7I.csv)
    -   [*Aedes* juvenile mortality data](activities/data/juvenilemortalityrateae.csv)
    -   [NLLS Practical Data](activities/data/nllsdataset.csv)

<br> <br>

## Intro to Bayes

-   [Lecture Slides](VB_Bayes1.qmd), [Practical 1](VB_Bayes_activity1.qmd)
-   Datasets:
    -   [Midge data](MidgeWingLength.csv)

<br> <br>

## Bayesian computation and MCMC

-   [Lecture Slides](VB_Bayes2.qmd), [Practical 2A](VB_Bayes_activity2.Qmd)

<br> <br>

## `bayesTPC`

-   [Practical](VB_Bayes_activity2B.qmd) 
-   Datasets:
    -  [*Aedes* data](AeaegyptiTraitData.csv) 
