---
title: "2023 Training Schedule"
description: "Schedule for synchronous training and suggestions for asynchronous study"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

[Main materials](materials.qmd)

# Pre-workshop

We will be using [R](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have R (version 3.6 or higher) installed.

You may use any IDE/ GUI for R (VScode, RStudio, Emacs, etc). For most people, [RStudio](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and test it before the workshop. We will have a channel on Slack dedicated to software/hardware issues and troubleshooting.

We will also be using Slack for additional support during the training. Please have these installed in advance. We are assuming familiarity with R basics. In addition, we recommend that you do the following:

1.  Go to [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html), and read+work through the [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html) up to the section on Writing R code. Of course, keep going if you want (although we will cover some similar materials here).

2.  Review background on [introductory probability and statistics](Stats_review.qmd) ([solutions to exercises](Stats_review_soln.qmd))

Once you have completed the pre-work and set-up tasks, you should get yourself familiar with the [VectorByte Training materials](materials.html). You will choose a starting point based on your previous experience. This will be in the form of slack channels labeled based on interest. From there you will group yourself (based on whatever you like, but keep in mind time zones and language preferences) and a demonstrator will be matched with your group.

Much of the synchronous time is planned to be dedicated to helping you work through exercises and activities. Thus you'll want to watch the videos and take a look at the slides off line (likely starting earlier in the week for most participants). The small subset of live instruction portions is elaborated below.

<br> <br> <br>

# 17th July 2023

| Time | Activity | Materials |
|------|----------|-----------|
|      | Arrival  |           |

<br> <br> <br>

# 18th July 2023 (08:30 - 17:00)

| Time  | Activity                                      | Materials                                                     |
|--------------|------------------------|----------------------------------|
| 08:30 | Course overview                               |                                                               |
| 09:00 | Intro to traits                               | [Example](example.html)                                       |
| 10:30 | Break                                         |                                                               |
| 11:00 | VecTraits database                            | [VecTraits](https://vectorbyte.crc.nd.edu/vectraits-explorer) |
| 12:00 | Lunch                                         |                                                               |
| 13:00 | Tutorial: Data wrangling and visualizing data | [Data wrangling](data_wrangling.qmd)                          |
| 15:00 | Break                                         |                                                               |
| 15:30 | Statistical Analyses I: Linear models         | [Linear models](linear_mod_activity.qmd)                      |

<br> <br> <br>

# 19th July 2023 (08:30 - 17:00)

| Time  | Activity                                     | Materials                                           |
|-------|----------------------------------------------|-----------------------------------------------------|
| 08:30 | Q & A                                        |                                                     |
| 09:00 | Allometric analysis using LMs                | [Linear models](linear_mod_activity.qmd)            |
| 10:30 | Break                                        |                                                     |
| 11:00 | Linear vs. Nonlinear models                  | [Practical](VB_NLLS_activity.qmd)                   |
| 12:00 | Lunch                                        |                                                     |
| 13:00 | Intro to Bayes                               | [Lecture](VB_Bayes1.qmd); [Practical](VB_Bayes_activity1.qmd)                 |
| 14:00 | Break                                        |                                                     |
| 14:15 | Bayes comp. (lecture and practical)          |                                                     |
| 15:15 | Break                                        |                                                     |
| 15:30 | TPCs practical                               |                                                     |

<br> <br> <br>

# 20th July 2023 (10:00 - 1:00)

| Time  | Activity                          | Materials |
|-------|-----------------------------------|-----------|
| 8:30  | Q & A                             |           |
| 9:00  | Work on analysis                  |           |
| 10:30 | Break                             |           |
| 11:00 | Work on analysis                  |           |
| 12:00 | Lunch                             |           |
| 13:00 | Continue analysis/present project |           |
| 15:00 | Break                             |           |
| 15:30 | Presentations                     |           |
| 16:30 | Data uploads                      |           |

<br> <br> <br>

# 21st July 2023

| Time | Activity | Materials |
|------|----------|-----------|
|      | Travel   |           |

<br> <br> <br>

# Post-workshop

Enjoy using these new techniques and databases!

<br> <br> <br>
